docker now has local directory for the immudb database

diff --git a/scripts/getimmudb b/scripts/getimmudb
--- a/scripts/getimmudb
+++ b/scripts/getimmudb
@@ -69,16 +69,17 @@ if [ $( $SUDO docker ps -a | grep immudb | wc -l ) -gt 0 ]; then
 else
   immudbexist=0
 fi
-
 logit "immudb not yet present  - OK $(date)"
 
 # Alloate database directory locally for backups etc. 
-mkdir -p /opt/immudb/db/
+mkdir -p /opt/immudb/db/ || echo "${red}😬 Cannot allocate /opt/immudb/db for immmudb audit database. Exciting...${reset}"; exit 1
+logit "allocated /opt/immudb/db - OK $(date)"
+
 # get immudb container now
 $SUDO docker run --restart always --publish 3322:3322 -d  -v /opt/immudb/db:/var/lib/immudb --name immudb codenotary/immudb:latest || "${red}Catastrophic error. Exiting...${reset}"; exit 1
+logit "ran docker run codenotary/immudb - OK $(date)"
 
 # now let's check if immudb is running. 
-
 if [ $( $SUDO docker ps -a | grep immudb | wc -l ) -gt 0 ]; then
   echo "${yellow}immudb is now  installed. Good!${reset}"
 else
